### ISSUE TITLE
Wildcards in template_paths?

### ISSUE THREAD

**Issue by binaryfire** [bladestan/bladestan#41]
Great package! Is it possible to use wildcards in template paths? Eg:

```
parameters:
    bladestan:
        template_paths:
            # default
            - resources/views
            - modules/*/views
```
